
const state = { screen:'home', setup:{ exam:'WAEC', level:'Secondary School', subject:'Mathematics', count:10, duration:10 }, examQuestions:[], current:0, answers:{}, endTime:null, timer:null, review:null };
const $ = sel => document.querySelector(sel);
const save = (k,v)=>localStorage.setItem(k,JSON.stringify(v));
const load = (k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const histories = ()=>load('myExams.history',[]);
function unique(key, list=QUESTION_BANK){ return [...new Set(list.map(q=>q[key]))].sort(); }
function render(){ clearInterval(state.timer); const root=$('#app'); root.innerHTML = `<div class="wrap">${screens[state.screen]()}</div>`; afterRender(); }
const screens={
 home(){return `<section class="hero"><div class="brand"><div class="logo">ME</div><div><div class="title">MY EXAMS APP</div><div class="sub">WAEC, NECO, JAMB and tertiary practice in one pocket.</div></div></div><div class="notice"><b>Content note:</b> This MVP uses original exam-style questions, explanations and source references. You can later replace/add licensed past questions through the same question-bank format.</div><div class="grid"><div class="card"><h3>Start Exam</h3><p class="muted">Timed CBT practice with instant score and review.</p><button class="btn" onclick="go('setup')">Start Exam</button></div><div class="card"><h3>Practice by Topic</h3><p class="muted">Pick subject and topic, then answer focused questions.</p><button class="btn secondary" onclick="go('topics')">Practice Topic</button></div><div class="card"><h3>Past Results</h3><p class="muted">Track progress and reopen reviews.</p><button class="btn secondary" onclick="go('history')">View History</button></div><div class="card challenge"><h3>Quiz Challenge</h3><p class="muted">Daily challenge and leaderboard placeholder for Phase 2.</p><button class="btn secondary" onclick="dailyChallenge()">Try 5-Question Sprint</button></div></div></section>`},
 setup(){ const exams=unique('exam'), levels=unique('level'), subjects=unique('subject'); return `<div class="topbar"><b>Exam Setup</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card"><div class="grid"><div class="field"><label>Exam Type</label><select id="exam">${opts(exams,state.setup.exam)}</select></div><div class="field"><label>Level</label><select id="level">${opts(levels,state.setup.level)}</select></div><div class="field"><label>Subject</label><select id="subject">${opts(subjects,state.setup.subject)}</select></div><div class="field"><label>Questions</label><select id="count">${opts([5,10,20,40],state.setup.count)}</select></div><div class="field"><label>Duration</label><select id="duration">${opts([5,10,20,40],state.setup.duration)} </select></div></div><button class="btn good" onclick="startExam()">Start Exam</button></div>`},
 exam(){ const q=state.examQuestions[state.current]; return `<div class="topbar"><div class="row"><span class="pill">${state.setup.exam}</span><span class="pill">${state.setup.subject}</span><span class="pill">Question ${state.current+1}/${state.examQuestions.length}</span></div><div class="row"><span class="pill" id="timer">--:--</span><button class="btn small danger" onclick="submitExam()">Submit</button></div></div><div class="card"><div class="muted">Topic: ${q.topic}</div><div class="question">${q.question}</div>${q.options.map((o,i)=>`<button class="option ${state.answers[q.id]===i?'active':''}" onclick="pick('${q.id}',${i})"><b>${String.fromCharCode(65+i)}.</b> ${o}</button>`).join('')}<div class="row" style="justify-content:space-between;margin-top:12px"><button class="btn secondary" onclick="prevQ()">Previous</button><button class="btn" onclick="nextQ()">Next</button></div></div>`},
 result(){ const r=state.review; return `<div class="topbar"><b>Result</b><button class="btn small secondary" onclick="go('home')">Home</button></div><div class="card"><div class="score">${r.score}/${r.total}</div><h2>${r.percent}%</h2><p class="muted">${r.exam} • ${r.subject} • ${new Date(r.date).toLocaleString()}</p><div class="row"><button class="btn" onclick="go('review')">Review Answers</button><button class="btn secondary" onclick="go('setup')">Try Again</button></div></div>`},
 review(){ const r=state.review; return `<div class="topbar"><b>Answer Review</b><button class="btn small secondary" onclick="go('result')">Back</button></div>${r.items.map((it,idx)=>`<div class="card" style="margin-bottom:10px"><div class="pill">${idx+1}. ${it.topic}</div><div class="question">${it.question}</div>${it.options.map((o,i)=>`<div class="option ${i===it.correctIndex?'correct':''} ${i===it.selected&&i!==it.correctIndex?'wrong':''}"><b>${String.fromCharCode(65+i)}.</b> ${o}</div>`).join('')}<p><b>Explanation:</b> ${it.explanation}</p><div class="src">Source reference: ${it.sourceNote}</div></div>`).join('')}`},
 history(){ const h=histories(); return `<div class="topbar"><b>Past Results</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card">${h.length?`<table class="table"><thead><tr><th>Date</th><th>Exam</th><th>Subject</th><th>Score</th><th></th></tr></thead><tbody>${h.map((r,i)=>`<tr><td>${new Date(r.date).toLocaleDateString()}</td><td>${r.exam}</td><td>${r.subject}</td><td>${r.score}/${r.total}</td><td><button class="btn small secondary" onclick="openHistory(${i})">Open</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">No results yet.</p>'}</div>`},
 topics(){ const subjects=unique('subject'); return `<div class="topbar"><b>Practice by Topic</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card"><div class="field"><label>Subject</label><select id="subjectTopic" onchange="renderTopicList()">${opts(subjects,state.setup.subject)}</select></div><div id="topicList"></div></div>`}
};
function opts(arr,val){return arr.map(x=>`<option value="${x}" ${String(x)===String(val)?'selected':''}>${x}</option>`).join('')}
function go(s){state.screen=s;render()} function afterRender(){ if(state.screen==='exam') tick(); if(state.screen==='topics') renderTopicList(); }
function startExam(){ ['exam','level','subject','count','duration'].forEach(id=>state.setup[id]=isNaN($(`#${id}`).value)?$(`#${id}`).value:Number($(`#${id}`).value)); let pool=QUESTION_BANK.filter(q=>q.exam===state.setup.exam && q.subject===state.setup.subject); if(pool.length<state.setup.count) pool=QUESTION_BANK.filter(q=>q.subject===state.setup.subject); state.examQuestions=shuffle(pool).slice(0,state.setup.count); state.current=0; state.answers={}; state.endTime=Date.now()+state.setup.duration*60000; state.screen='exam'; render(); }
function dailyChallenge(){ state.setup={exam:'WAEC',level:'Secondary School',subject:'Mathematics',count:5,duration:5}; state.examQuestions=shuffle(QUESTION_BANK).slice(0,5); state.current=0; state.answers={}; state.endTime=Date.now()+5*60000; state.screen='exam'; render(); }
function shuffle(a){return [...a].sort(()=>Math.random()-0.5)} function pick(id,i){state.answers[id]=i;render()} function nextQ(){if(state.current<state.examQuestions.length-1){state.current++;render()}} function prevQ(){if(state.current>0){state.current--;render()}}
function tick(){ const el=$('#timer'); const rem=Math.max(0,Math.floor((state.endTime-Date.now())/1000)); const m=String(Math.floor(rem/60)).padStart(2,'0'), s=String(rem%60).padStart(2,'0'); if(el) el.textContent=`Time ${m}:${s}`; if(rem<=0) submitExam(); else state.timer=setTimeout(tick,1000); }
function submitExam(){ const items=state.examQuestions.map(q=>({...q, selected: state.answers[q.id] ?? null, correct: state.answers[q.id]===q.correctIndex})); const score=items.filter(x=>x.correct).length; const r={date:new Date().toISOString(),exam:state.setup.exam,level:state.setup.level,subject:state.setup.subject,score,total:items.length,percent:Math.round(score/items.length*100),items}; state.review=r; save('myExams.history',[r,...histories()].slice(0,50)); state.screen='result'; render(); }
function openHistory(i){ state.review=histories()[i]; state.screen='review'; render(); }
function renderTopicList(){ const subj=$('#subjectTopic')?.value || state.setup.subject; const topics=unique('topic',QUESTION_BANK.filter(q=>q.subject===subj)); $('#topicList').innerHTML=`<h3>${subj} Topics</h3><div class="grid">${topics.map(t=>`<div class="card"><b>${t}</b><p class="muted">Focused 5-question drill.</p><button class="btn small" onclick="startTopic('${subj}','${t.replace(/'/g,"\\'")}')">Start</button></div>`).join('')}</div>`; }
function startTopic(subject,topic){ state.setup={exam:'Topic Practice',level:'Secondary School',subject,count:5,duration:5}; state.examQuestions=shuffle(QUESTION_BANK.filter(q=>q.subject===subject&&q.topic===topic)).slice(0,5); if(!state.examQuestions.length) state.examQuestions=shuffle(QUESTION_BANK.filter(q=>q.subject===subject)).slice(0,5); state.current=0; state.answers={}; state.endTime=Date.now()+5*60000; state.screen='exam'; render(); }
render();
