const state = {
  screen:'home',
  setup:{ exam:'WAEC', section:'Objective', level:'Secondary School', subject:'Mathematics', count:10, duration:10 },
  examQuestions:[], current:0, answers:{}, theoryAnswers:{}, endTime:null, timer:null, review:null
};
const $ = sel => document.querySelector(sel);
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const histories=()=>load('myExams.v2.history',[]);
function available(list,key){return [...new Set(list.map(x=>x[key]).filter(Boolean))].sort()}
function examMeta(exam){
  if(['WAEC','NECO','NABTEB','JAMB'].includes(exam)) return {level:'Secondary School', locked:true};
  return {level:'Tertiary Institution', locked:false};
}
function poolForSetup(){
  return QUESTION_BANK.filter(q=>q.exam===state.setup.exam && q.section===state.setup.section && q.subject===state.setup.subject);
}
function render(){clearTimeout(state.timer);document.querySelector('#app').innerHTML=`<div class="wrap">${screens[state.screen]()}</div>`;afterRender()}
const screens={
  home(){return `<section class="hero"><div class="brand"><div class="logo">ME</div><div><div class="title">MY EXAMS APP</div><div class="sub">Objective + theory practice for WAEC, NECO, NABTEB, JAMB and later tertiary aptitude exams.</div></div></div><div class="notice"><b>Structure update:</b> WAEC, NECO, NABTEB and JAMB are locked to Secondary School by default. University, Polytechnic and College versions are separated under tertiary aptitude.</div><div class="grid"><div class="card"><h3>Start Exam</h3><p class="muted">Choose objective or theory, then practise under timed exam conditions.</p><button class="btn" onclick="go('setup')">Start Exam</button></div><div class="card"><h3>Practice by Topic</h3><p class="muted">Drill weak topics in objective or theory format.</p><button class="btn secondary" onclick="go('topics')">Practice Topic</button></div><div class="card"><h3>Past Results</h3><p class="muted">Review scores, answers, marking guides and explanations.</p><button class="btn secondary" onclick="go('history')">View History</button></div><div class="card"><h3>Source References</h3><p class="muted">Reference notes for public question sources used during content gathering.</p><button class="btn secondary" onclick="go('sources')">Open Sources</button></div></div></section>`},
  setup(){
    const exams=available(QUESTION_BANK,'exam');
    const meta=examMeta(state.setup.exam);
    const filtered=QUESTION_BANK.filter(q=>q.exam===state.setup.exam && q.section===state.setup.section);
    const subjects=available(filtered,'subject');
    if(!subjects.includes(state.setup.subject)) state.setup.subject=subjects[0] || 'Mathematics';
    return `<div class="topbar"><b>Exam Setup</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card"><div class="grid"><div class="field"><label>Exam Type</label><select id="exam" onchange="onExamChange()">${opts(exams,state.setup.exam)}</select></div><div class="field"><label>Paper Section</label><select id="section" onchange="onSectionChange()">${opts(['Objective','Theory'],state.setup.section)}</select></div><div class="field"><label>Level</label><input id="level" value="${meta.level}" disabled /></div><div class="field"><label>Subject</label><select id="subject">${opts(subjects,state.setup.subject)}</select></div><div class="field"><label>Questions</label><select id="count">${opts([1,2,5,10,20,40],state.setup.count)}</select></div><div class="field"><label>Duration</label><select id="duration">${opts([5,10,20,40,60,120],state.setup.duration)}</select></div></div><div class="notice">For real WAEC-style structure, choose <b>Objective</b> for multiple-choice questions or <b>Theory</b> for written answers with marking guide.</div><button class="btn good" onclick="startExam()">Start Exam</button></div>`
  },
  exam(){
    const q=state.examQuestions[state.current];
    const isTheory=q.section==='Theory';
    return `<div class="topbar"><div class="row"><span class="pill">${q.exam}</span><span class="pill">${q.section}</span><span class="pill">${q.subject}</span><span class="pill">Question ${state.current+1}/${state.examQuestions.length}</span></div><div class="row"><span class="pill" id="timer">--:--</span><button class="btn small danger" onclick="submitExam()">Submit</button></div></div><div class="card"><div class="row"><span class="tag">${q.topic}</span><span class="tag">${q.year}</span></div><div class="question">${q.question}</div>${isTheory?theoryBox(q):objectiveBox(q)}<div class="row" style="justify-content:space-between;margin-top:12px"><button class="btn secondary" onclick="prevQ()">Previous</button><button class="btn" onclick="nextQ()">Next</button></div></div>`
  },
  result(){const r=state.review;return `<div class="topbar"><b>Result</b><button class="btn small secondary" onclick="go('home')">Home</button></div><div class="card"><div class="score">${r.scoreLabel}</div><h2>${r.title}</h2><p class="muted">${r.exam} • ${r.section} • ${r.subject} • ${new Date(r.date).toLocaleString()}</p><div class="row"><button class="btn" onclick="go('review')">Review Answers</button><button class="btn secondary" onclick="go('setup')">Try Again</button></div></div>`},
  review(){const r=state.review;return `<div class="topbar"><b>Review</b><button class="btn small secondary" onclick="go('result')">Back</button></div>${r.items.map((it,i)=>reviewItem(it,i)).join('')}`},
  history(){const h=histories();return `<div class="topbar"><b>Past Results</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card">${h.length?`<table class="table"><thead><tr><th>Date</th><th>Exam</th><th>Section</th><th>Subject</th><th>Score</th><th></th></tr></thead><tbody>${h.map((r,i)=>`<tr><td>${new Date(r.date).toLocaleDateString()}</td><td>${r.exam}</td><td>${r.section}</td><td>${r.subject}</td><td>${r.scoreLabel}</td><td><button class="btn small secondary" onclick="openHistory(${i})">Open</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">No results yet.</p>'}</div>`},
  topics(){const subjects=available(QUESTION_BANK,'subject');return `<div class="topbar"><b>Practice by Topic</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card"><div class="split"><div class="field"><label>Subject</label><select id="topicSubject" onchange="renderTopicList()">${opts(subjects,state.setup.subject)}</select></div><div class="field"><label>Section</label><select id="topicSection" onchange="renderTopicList()">${opts(['Objective','Theory'],state.setup.section)}</select></div></div><div id="topicList"></div></div>`},
  sources(){return `<div class="topbar"><b>Source References</b><button class="btn small secondary" onclick="go('home')">Back</button></div><div class="card"><p class="muted">Reference notes can stay in the app so users know the question bank was built from public exam-prep sources. Bulk licensed import can be added later.</p>${SOURCE_REFERENCES.map(s=>`<div class="markbox"><b>${s.name}</b><p class="muted">${s.note}</p><div class="src">${s.url}</div></div>`).join('')}</div>`}
};
function opts(arr,val){return arr.map(x=>`<option value="${x}" ${String(x)===String(val)?'selected':''}>${x}</option>`).join('')}
function go(s){state.screen=s;render()} function afterRender(){if(state.screen==='exam')tick();if(state.screen==='topics')renderTopicList()}
function onExamChange(){state.setup.exam=$('#exam').value;state.setup.level=examMeta(state.setup.exam).level;render()} function onSectionChange(){state.setup.section=$('#section').value;render()}
function theoryBox(q){return `<div class="field"><label>Your Answer</label><textarea id="ans_${q.id}" oninput="state.theoryAnswers['${q.id}']=this.value" placeholder="Type your answer here. In Phase 2, students can snap/upload theory answers for AI marking.">${state.theoryAnswers[q.id]||''}</textarea></div><div class="notice">MVP theory mode saves your answer and shows a marking guide after submission. AI scoring/image marking comes in Phase 2.</div>`}
function objectiveBox(q){return q.options.map((o,i)=>`<button class="option ${state.answers[q.id]===i?'active':''}" onclick="pick('${q.id}',${i})"><b>${String.fromCharCode(65+i)}.</b> ${o}</button>`).join('')}
function startExam(){['exam','section','subject','count','duration'].forEach(id=>{const el=$('#'+id);state.setup[id]=isNaN(el.value)?el.value:Number(el.value)});state.setup.level=examMeta(state.setup.exam).level;let pool=poolForSetup();if(pool.length<state.setup.count) pool=QUESTION_BANK.filter(q=>q.exam===state.setup.exam&&q.section===state.setup.section);if(!pool.length) pool=QUESTION_BANK.filter(q=>q.section===state.setup.section);state.examQuestions=shuffle(pool).slice(0,Math.min(state.setup.count,pool.length));state.current=0;state.answers={};state.theoryAnswers={};state.endTime=Date.now()+state.setup.duration*60000;go('exam')}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)} function pick(id,i){state.answers[id]=i;render()} function prevQ(){if(state.current>0){state.current--;render()}} function nextQ(){if(state.current<state.examQuestions.length-1){state.current++;render()}}
function tick(){const el=$('#timer');const rem=Math.max(0,Math.floor((state.endTime-Date.now())/1000));const m=String(Math.floor(rem/60)).padStart(2,'0'),s=String(rem%60).padStart(2,'0');if(el)el.textContent=`Time ${m}:${s}`;if(rem<=0)submitExam();else state.timer=setTimeout(tick,1000)}
function submitExam(){const items=state.examQuestions.map(q=>q.section==='Theory'?{...q,studentAnswer:state.theoryAnswers[q.id]||''}:{...q,selected:state.answers[q.id]??null,correct:state.answers[q.id]===q.correctIndex});let score=items.filter(x=>x.correct).length;let total=items.length;let isTheory=state.setup.section==='Theory';const r={date:new Date().toISOString(),exam:state.setup.exam,level:state.setup.level,section:state.setup.section,subject:state.setup.subject,score,total,scoreLabel:isTheory?'Marking guide':' '+score+'/'+total,title:isTheory?'Theory submitted':'Score '+Math.round((score/Math.max(total,1))*100)+'%',items};state.review=r;save('myExams.v2.history',[r,...histories()].slice(0,50));go('result')}
function reviewItem(it,i){if(it.section==='Theory')return `<div class="card" style="margin-bottom:10px"><div class="row"><span class="pill">${i+1}. ${it.topic}</span><span class="pill">${it.maxScore} marks</span></div><div class="question">${it.question}</div><div class="markbox"><b>Your Answer</b><p>${(it.studentAnswer||'<span class="muted">No answer typed.</span>')}</p></div><div class="markbox"><b>Expected Points / Marking Guide</b><ol>${it.expectedPoints.map(p=>`<li>${p}</li>`).join('')}</ol><p><b>Breakdown:</b> ${it.explanation}</p></div><div class="src">Source: ${it.source}${it.sourceUrl?' • '+it.sourceUrl:''}</div></div>`;return `<div class="card" style="margin-bottom:10px"><div class="row"><span class="pill">${i+1}. ${it.topic}</span><span class="pill">${it.year}</span></div><div class="question">${it.question}</div>${it.options.map((o,idx)=>`<div class="option ${idx===it.correctIndex?'correct':''} ${idx===it.selected&&idx!==it.correctIndex?'wrong':''}"><b>${String.fromCharCode(65+idx)}.</b> ${o}</div>`).join('')}<p><b>Breakdown:</b> ${it.explanation}</p><div class="src">Source: ${it.source}${it.sourceUrl?' • '+it.sourceUrl:''}</div></div>`}
function openHistory(i){state.review=histories()[i];go('review')}
function renderTopicList(){const subj=$('#topicSubject')?.value||state.setup.subject;const sec=$('#topicSection')?.value||state.setup.section;const topics=available(QUESTION_BANK.filter(q=>q.subject===subj&&q.section===sec),'topic');$('#topicList').innerHTML=`<h3>${subj} • ${sec}</h3><div class="grid">${topics.map(t=>`<div class="card"><b>${t}</b><p class="muted">Focused ${sec.toLowerCase()} drill.</p><button class="btn small" onclick="startTopic('${subj}','${sec}','${t.replace(/'/g,"\\'")}')">Start</button></div>`).join('')||'<p class="muted">No topics found.</p>'}</div>`}
function startTopic(subject,section,topic){let pool=QUESTION_BANK.filter(q=>q.subject===subject&&q.section===section&&q.topic===topic);let q=pool[0];state.setup={exam:q?.exam||'WAEC',level:q?.level||'Secondary School',section,subject,count:Math.min(5,pool.length),duration:5};state.examQuestions=shuffle(pool).slice(0,5);state.current=0;state.answers={};state.theoryAnswers={};state.endTime=Date.now()+5*60000;go('exam')}
render();
