const SOURCE_REFERENCES = [
  { name:'WAEC e-Learning Toolkit', url:'https://www.waeconline.org.ng/e-learning/', note:'Official WAEC learning/performance resource. Use for exam structure, weaknesses and official-style theory review.' },
  { name:'WAEC Civic Education Paper 2 WASSCE 2023 page', url:'https://www.waeconline.org.ng/e-learning/Civic/civic240mq1.html', note:'Official WAEC e-learning theory-question review page.' },
  { name:'MySchool WAEC classroom pages', url:'https://myschool.ng/classroom/english-language?exam_type=waec', note:'Public WAEC objective/theory practice listing; use only where licensing/permission is confirmed.' },
  { name:'MySchoolGist WAEC past-question downloads', url:'https://myschoolgist.com/news/free-waec-past-questions-and-answers/', note:'Public directory of WAEC past-question PDFs and sample-question links.' },
  { name:'KOFA Study WAEC objective and theory practice', url:'https://www.kofastudy.com/waec/', note:'Public WAEC objective/theory practice source.' },
  { name:'SchoolNGR WAEC/JAMB classroom', url:'https://www.schoolngr.com/classroom/waec', note:'Public past-question classroom listing.' }
];

const QUESTION_BANK = [
  // Real sourced samples kept small; explanations and marking guides are original.
  {id:'WAEC-CIV-2023-T1', exam:'WAEC', level:'Secondary School', section:'Theory', subject:'Civic Education', topic:'Citizenship and Nation Building', year:'2023', source:'WAEC e-Learning Civic Education Paper 2 WASSCE 2023', sourceUrl:'https://www.waeconline.org.ng/e-learning/Civic/civic240mq1.html', question:'Identify five values of civic education. Explain any five ways citizenship can contribute to nation building.', expectedPoints:['Values include honesty, tolerance, discipline, patriotism and cooperation.','Citizens contribute by obeying laws, paying taxes, voting, protecting public property and promoting peace.','Answers should explain, not merely list, the contribution to nation building.'], maxScore:10, explanation:'This is a theory question. A strong answer separates the two parts: first list five civic values, then explain five practical ways responsible citizens help national growth.'},
  {id:'WAEC-ENG-OBJ-S1', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'English', topic:'Grammar', year:'2024', source:'MySchool WAEC English public classroom listing', sourceUrl:'https://myschool.ng/classroom/english-language?exam_type=waec', question:'Certain tasks may be unpleasant at first, but gradually one may get ____ them.', options:['about','at','to','with'], correctIndex:2, explanation:'The correct expression is “get used to them.” The preposition “to” completes the idiom.'},
  {id:'JAMB-ENG-1978-S1', exam:'JAMB', level:'Secondary School', section:'Objective', subject:'English', topic:'Vocabulary', year:'1978', source:'MySchool JAMB English public classroom listing', sourceUrl:'https://myschool.ng/classroom/english-language?exam_type=jamb', question:'Only the small fry gets punished for such social misdemeanours. What does “small fry” mean?', options:['small boys','unimportant people','frightened people','frivolous people','inexperienced people'], correctIndex:1, explanation:'“Small fry” means people considered unimportant or powerless, especially compared with more influential people.'},

  // Original MVP bank matching real exam structure.
  {id:'WAEC-MATH-O1', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'Mathematics', topic:'Algebra', year:'Practice', source:'Original exam-style item based on WAEC syllabus format', sourceUrl:'', question:'If 3x + 5 = 20, find x.', options:['3','5','7','15'], correctIndex:1, explanation:'Subtract 5 from both sides: 3x = 15. Divide by 3, so x = 5.'},
  {id:'WAEC-MATH-O2', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'Mathematics', topic:'Indices', year:'Practice', source:'Original exam-style item based on WAEC syllabus format', sourceUrl:'', question:'Simplify 2³ × 2⁴.', options:['2⁷','2¹²','4⁷','16'], correctIndex:0, explanation:'When multiplying powers with the same base, add the powers: 2³ × 2⁴ = 2⁷.'},
  {id:'WAEC-MATH-T1', exam:'WAEC', level:'Secondary School', section:'Theory', subject:'Mathematics', topic:'Simultaneous Equations', year:'Practice', source:'Original exam-style theory item based on WAEC syllabus format', sourceUrl:'', question:'Solve the simultaneous equations: 2x + y = 11 and x - y = 1.', expectedPoints:['From x - y = 1, x = y + 1.','Substitute into 2x + y = 11 to get 2(y + 1) + y = 11.','3y + 2 = 11, so y = 3 and x = 4.'], maxScore:5, explanation:'Use substitution. Express x in terms of y, substitute into the first equation, solve y, then find x.'},
  {id:'WAEC-ENG-O1', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'English', topic:'Grammar', year:'Practice', source:'Original exam-style item based on WAEC English format', sourceUrl:'', question:'Choose the correct sentence.', options:['He do not like rice.','He does not like rice.','He did not likes rice.','He don’t likes rice.'], correctIndex:1, explanation:'With “he”, use “does not”; after “does”, the main verb remains “like”.'},
  {id:'WAEC-ENG-T1', exam:'WAEC', level:'Secondary School', section:'Theory', subject:'English', topic:'Letter Writing', year:'Practice', source:'Original exam-style theory item based on WAEC English format', sourceUrl:'', question:'Write a letter to your friend explaining three ways students can prepare effectively for external examinations.', expectedPoints:['Correct informal letter format: address, date, greeting and closing.','Explain three preparation methods clearly.','Use organized paragraphs and correct grammar.'], maxScore:20, explanation:'The answer should be an informal letter, not bullet points only. Award marks for format, content, organization, expression and mechanical accuracy.'},
  {id:'WAEC-BIO-O1', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'Biology', topic:'Cell Biology', year:'Practice', source:'Original exam-style item based on WAEC Biology format', sourceUrl:'', question:'Which organelle is mainly responsible for releasing energy in a cell?', options:['Ribosome','Mitochondrion','Vacuole','Nucleus'], correctIndex:1, explanation:'The mitochondrion is the site of aerobic respiration where usable energy is released.'},
  {id:'WAEC-BIO-T1', exam:'WAEC', level:'Secondary School', section:'Theory', subject:'Biology', topic:'Photosynthesis', year:'Practice', source:'Original exam-style theory item based on WAEC Biology format', sourceUrl:'', question:'State four factors that affect the rate of photosynthesis and explain how any two of them affect the process.', expectedPoints:['Light intensity, carbon dioxide concentration, temperature and chlorophyll/water availability are acceptable.','Higher light intensity increases rate up to a limit.','Low carbon dioxide reduces the rate because it is a raw material.'], maxScore:8, explanation:'List four factors first, then choose two and explain their effects clearly.'},
  {id:'WAEC-CHEM-O1', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'Chemistry', topic:'Acids and Bases', year:'Practice', source:'Original exam-style item based on WAEC Chemistry format', sourceUrl:'', question:'A solution with pH 2 is best described as', options:['strongly acidic','weakly alkaline','neutral','strongly alkaline'], correctIndex:0, explanation:'The lower the pH below 7, the more acidic the solution. pH 2 is strongly acidic.'},
  {id:'WAEC-CHEM-T1', exam:'WAEC', level:'Secondary School', section:'Theory', subject:'Chemistry', topic:'Separation Techniques', year:'Practice', source:'Original exam-style theory item based on WAEC Chemistry format', sourceUrl:'', question:'Describe how you would separate a mixture of sand, salt and water in the laboratory.', expectedPoints:['Filter the mixture to remove sand as residue.','Evaporate the filtrate to recover salt.','Water may be recovered by distillation instead of simple evaporation.'], maxScore:6, explanation:'The answer should follow the correct order: filtration separates insoluble sand; evaporation or distillation separates dissolved salt from water.'},
  {id:'WAEC-PHY-O1', exam:'WAEC', level:'Secondary School', section:'Objective', subject:'Physics', topic:'Motion', year:'Practice', source:'Original exam-style item based on WAEC Physics format', sourceUrl:'', question:'A car travels 100 m in 5 s. Its average speed is', options:['5 m/s','10 m/s','20 m/s','50 m/s'], correctIndex:2, explanation:'Average speed = distance ÷ time = 100 ÷ 5 = 20 m/s.'},
  {id:'WAEC-PHY-T1', exam:'WAEC', level:'Secondary School', section:'Theory', subject:'Physics', topic:'Electricity', year:'Practice', source:'Original exam-style theory item based on WAEC Physics format', sourceUrl:'', question:'A 6 Ω resistor is connected to a 12 V battery. Calculate the current flowing through the resistor and state the law used.', expectedPoints:['Use Ohm’s law: V = IR.','I = V/R = 12/6 = 2 A.','State that current is directly proportional to voltage at constant temperature.'], maxScore:5, explanation:'Apply Ohm’s law. Divide voltage by resistance to obtain current in amperes.'},
  {id:'NECO-GOV-O1', exam:'NECO', level:'Secondary School', section:'Objective', subject:'Government', topic:'Democracy', year:'Practice', source:'Original exam-style item based on NECO Government format', sourceUrl:'', question:'A major feature of democracy is', options:['military rule','one-party dictatorship','periodic elections','rule by decree'], correctIndex:2, explanation:'Democracy requires citizens to choose leaders through regular, free and fair elections.'},
  {id:'NECO-GOV-T1', exam:'NECO', level:'Secondary School', section:'Theory', subject:'Government', topic:'Separation of Powers', year:'Practice', source:'Original exam-style theory item based on NECO Government format', sourceUrl:'', question:'Explain four reasons why separation of powers is important in a democratic state.', expectedPoints:['It prevents abuse of power.','It promotes checks and balances.','It protects citizens’ rights.','It improves accountability and efficiency.'], maxScore:8, explanation:'Each reason should be explained. Do not merely list points without showing why they matter.'},
  {id:'NECO-ECON-O1', exam:'NECO', level:'Secondary School', section:'Objective', subject:'Economics', topic:'Demand and Supply', year:'Practice', source:'Original exam-style item based on NECO Economics format', sourceUrl:'', question:'When price rises and quantity demanded falls, this illustrates the law of', options:['supply','demand','returns','utility'], correctIndex:1, explanation:'The law of demand states that, all things being equal, higher price leads to lower quantity demanded.'},
  {id:'NECO-ECON-T1', exam:'NECO', level:'Secondary School', section:'Theory', subject:'Economics', topic:'Production', year:'Practice', source:'Original exam-style theory item based on NECO Economics format', sourceUrl:'', question:'Define production and explain four factors of production.', expectedPoints:['Production is the creation of goods and services to satisfy wants.','Land means natural resources.','Labour means human effort.','Capital means man-made resources used in production.','Entrepreneur organizes other factors and bears risk.'], maxScore:10, explanation:'Start with a clear definition, then explain land, labour, capital and entrepreneur.'},
  {id:'NABTEB-ICT-O1', exam:'NABTEB', level:'Secondary School', section:'Objective', subject:'ICT', topic:'Computer Hardware', year:'Practice', source:'Original exam-style item based on NABTEB ICT format', sourceUrl:'', question:'Which of the following is an input device?', options:['Monitor','Printer','Keyboard','Speaker'], correctIndex:2, explanation:'A keyboard is used to enter data into the computer, so it is an input device.'},
  {id:'NABTEB-BUS-T1', exam:'NABTEB', level:'Secondary School', section:'Theory', subject:'Business Studies', topic:'Bookkeeping', year:'Practice', source:'Original exam-style theory item based on NABTEB Business Studies format', sourceUrl:'', question:'Explain the difference between cash sales and credit sales, giving one example of each.', expectedPoints:['Cash sales are paid for immediately.','Credit sales are paid for later.','Example of cash sale: goods sold and paid for at once.','Example of credit sale: goods sold to a customer on account.'], maxScore:6, explanation:'The answer should distinguish timing of payment and give clear examples.'},
  {id:'UNI-APT-O1', exam:'University Aptitude', level:'Tertiary Institution', section:'Objective', subject:'General Studies', topic:'Critical Reasoning', year:'Practice', source:'Original tertiary aptitude item', sourceUrl:'', question:'All diligent students revise daily. Ada revises daily. Which conclusion is most valid?', options:['Ada is diligent','Ada may be diligent','All students are Ada','No diligent student revises'], correctIndex:1, explanation:'The statement does not say everyone who revises daily is diligent. It only says diligent students revise daily, so Ada may be diligent.'},
  {id:'POLY-APT-O1', exam:'Polytechnic Aptitude', level:'Tertiary Institution', section:'Objective', subject:'Quantitative Reasoning', topic:'Percentages', year:'Practice', source:'Original tertiary aptitude item', sourceUrl:'', question:'A price rises from ₦2,000 to ₦2,500. What is the percentage increase?', options:['20%','25%','30%','50%'], correctIndex:1, explanation:'Increase = 500. Percentage increase = 500/2000 × 100 = 25%.'}
];
